language: node_js
addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base
    - r-cran-rcpp
    - r-cran-rjson
    - r-cran-rinside
node_js:
  - 'stable'
  - '5'
  - '4'
after_script:
  - npm run coveralls
